cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path, include
from orders import views


urlpatterns = [
    path('', views.order_create, name='order_create'),
]

ticketer/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from userSystem import views as user_views

app_name = 'mySite'

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/reread-logo.ico', permanent=True), name='favicon'),
    path('admin/', admin.site.urls),
    path('', include('mySite.urls')),


    # login system
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),

    # profile system
    path('profile/', user_views.view_profile, name='view_profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),

    path('profile/<str:username>/', user_views.other_user_profile, name='other_user_profile'),

    path('', include('benches.urls')),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),

    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from benches.models import Bench
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Bench, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Bench, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "mySite/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<div class="bg-white pl-12 pr-16 py-12 rounded-xl max-md:px-5">
    <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
      <div class="flex flex-col items-stretch w-[62%] max-md:w-full max-md:ml-0">
        <div
          class="flex flex-col mt-9 items-start max-md:max-w-full max-md:mt-10"
        >
          <a href="/" class="flex items-stretch gap-0">
            <img
              loading="lazy"
              srcset="https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/5924c26352200de65180c8ee2f87fa36c0b8c512e2747f88dc65a4ed585f7fb9?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"
              class="aspect-square object-contain object-center w-[51px] overflow-hidden shrink-0 max-w-full"
            />
            <div
              class="text-stone-900 text-xl font-semibold self-center grow whitespace-nowrap my-auto"
            >
              Вернуться
            </div>
        </a>
          <div
            class="self-stretch flex flex-col items-stretch mt-8 max-md:max-w-full"
          >
            <div
              class="bg-stone-300 w-[1030px] shrink-0 max-w-full h-[3px] mr-7 max-md:mr-2.5"
            ></div>
            <div
              class="text-stone-900 text-xl font-medium mt-12 max-md:max-w-full max-md:mt-10"
            >
              Корзина
            </div>
            <div
              class="text-stone-900 text-base font-medium mt-2 max-md:max-w-full"
            >

            </div>

            {% for item in cart %}
            {% with product=item.product %}
            <div class="shadow-sm bg-white flex w-[1030px] max-w-full items-stretch justify-between gap-5 mr-7 mt-14 pl-4 pr-10 py-4 rounded-xl max-md:flex-wrap max-md:justify-center max-md:mr-2.5 max-md:mt-10 max-md:pr-5"> 
                  <div class="max-md:max-w-full">
                    <div
                      class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0"
                    >
                      <div
                        class="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0"
                      >
                        <img
                          loading="lazy"
                          srcset="{{ product.get_avatar_url }}"
                          class="aspect-[0.96] object-contain object-center w-[135px] overflow-hidden shrink-0 max-w-full grow max-md:mt-8"
                        />
                      </div>
                      <div
                        class="flex flex-col items-stretch w-[67%] ml-5 max-md:w-full max-md:ml-0"
                      >
                        <div class="flex flex-col items-stretch my-auto max-md:mt-10">
                          <a href="/event/{{ product.id }}" class="text-stone-900 text-xl font-medium hover:text-red-500">
                            {{ product.name }}
                          </a>
                          <div
                            class="text-stone-900 text-base font-medium whitespace-nowrap mt-4"
                          >

                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="self-center flex gap-4 my-auto items-start">
                    <div
                      class="text-neutral-700 text-xl font-semibold leading-9 grow whitespace-nowrap mt-1.5"
                    >
                    {{ item.quantity }} билета по {{ item.price }} тг
                    </div>


                  </div>
                  <div
                    class="self-center flex items-center justify-between gap-5 my-auto"
                  >
                    <div
                      class="text-neutral-700 text-right text-xl font-medium my-auto"
                    >

                    </div>
                    <a href="{% url "cart:cart_remove" product.id%}">
                      <img
                      loading="lazy"
                      srcset="https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/480bc681d7b009f3619c392d69dbd76ff288ae34369e037aaf17acfa28f75367?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"
                      class="aspect-square object-contain object-center w-[32px] overflow-hidden self-stretch shrink-0 max-w-full"
                    />
                    </a>

                  </div>
                </div>
          </div>
          {% endwith %}
          {% endfor %}

          
        </div>

        <a href="{% url "orders:order_create" %}"
        class="bg-violet-500 flex w-auto gap-5 mt-12 pl-10 pr-9 py-8 rounded-xl max-md:max-w-full max-md:flex-wrap max-md:mt-10 max-md:px-5 w-1/6"
      >
        <div
          class="text-white text-3xl font-medium grow whitespace-nowrap self-stretch items-center justify-between gap-3.5"
        >
          Купить
        </div>
      </a>
      </div>

    </div>
  </div>
        
{% endblock %}