cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ticketer/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from userSystem import views as user_views

app_name = 'mySite'

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/reread-logo.ico', permanent=True), name='favicon'),
    path('admin/', admin.site.urls),
    path('', include('mySite.urls')),


    # login system
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),

    # profile system
    path('profile/', user_views.view_profile, name='view_profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),

    path('profile/<str:username>/', user_views.other_user_profile, name='other_user_profile'),

    path('', include('benches.urls')),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),

    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userSystem/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# login system
class CustomUser(AbstractUser):
    # Добавьте здесь дополнительные поля, если необходимо
    email = models.EmailField(unique=True)
    # ваша дополнительная информация
    # ...
    
    USERNAME_FIELD = 'username'  # или любое другое поле, которое вы хотите использовать для входа
    pass



class Profile(models.Model):
    LEVEL_CHOICES = [
        (0, 'Пользователь'),
        (1, 'Активный пользователь'),
        (2, 'Эксперт'),
        (3, 'Лидер'),
        (4, 'Администрация⭐'),
    ]

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, default='')
    surname = models.CharField(max_length=50, blank=True, default='')

    bio = models.TextField(blank=True)
    avatar = models.ImageField(default='default.png', upload_to='user_avatars/', blank=True, null=True)

    level = models.IntegerField(default=0, choices=LEVEL_CHOICES)

    def __str__(self):
        return self.user.username
    
    def get_avatar_url(self):
        if self.avatar:
            return self.avatar.url
        # Здесь вы можете вернуть путь к изображению по умолчанию или другую логику по вашему выбору
        return '/media/default.png'
    
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.user.username
        super(Profile, self).save(*args, **kwargs)

userSystem/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser, Profile

# login system
class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')  # Поля, которые будут отображаться на форме

class LoginForm(AuthenticationForm):
    # Вы можете добавить дополнительные поля, если необходимо
    class Meta:
        model = CustomUser

# profile system
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'surname', 'bio', 'avatar']

userSystem/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

from .models import CustomUser, Profile

from .forms import RegistrationForm, LoginForm, ProfileForm

# login system
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Автоматически входить пользователя после успешной регистрации
            return redirect('mySite:index')
    else:
        form = RegistrationForm()
    return render(request, 'userSystem/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('mySite:index')

    else:
        form = LoginForm()
    return render(request, 'userSystem/login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('mySite:index')


# profile system
@login_required
def view_profile(request):
    user_ip = request.META.get('REMOTE_ADDR', None)
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        # Если профиль не существует, создайте его здесь
        profile = Profile(user=request.user)
        profile.save()
    
    return render(request, 'userSystem/view_profile.html', {'profile': profile, 'user_ip': user_ip})

@login_required
def edit_profile(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        # Если профиль не существует, создайте его здесь
        profile = Profile(user=request.user)
        profile.save()

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            if request.POST.get('delete_avatar'):
                profile.avatar.delete()
                profile.avatar = None
                profile.save()
            return redirect('view_profile')

    else:
        form = ProfileForm(instance=profile)

    return render(request, 'userSystem/edit_profile.html', {'form': form, 'profile': profile})

def other_user_profile(request, username):
    try:
        user = get_object_or_404(CustomUser, username=username)
        profile = Profile.objects.get(user=user)
    except Http404:
        error_message = f"Профиль пользователя {username} не найден."
        return render(request, 'userSystem/other_user_profile.html', {'error_message': error_message}, status=404)

    return render(request, 'userSystem/other_user_profile.html', {'profile': profile})

userSystem/templates/userSystem/edit_profile.html
{% extends "mySite/base.html" %}
{% load static %}
{% load i18n %}
{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extra_css %}
        <link rel="stylesheet" href="{% static 'mySite/register.css' %}">
    {% endblock %}
    {% block title %}edit profile{% endblock %}
</head>
<body>
    <div class="profile">
        {% include 'mySite/base.html' %} 
        <div class="container">
            <div class="profile-container">
                {% block content %}
                    <h1>Редактирование профиля</h1>
                    <p><strong>Имя пользователя:</strong> {{ user.username }}</p>

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="id_name">Имя:</label>
                        <input type="text" id="id_name" name="name" value="{{ profile.name }}">
                        <br>
                        <label for="id_surname">Фамилия:</label>
                        <input type="text" id="id_surname" name="surname" value="{{ profile.surname }}">
                        <br>
                        <label for="id_bio">Биография:</label>
                        <textarea id="id_bio" name="bio">{{ profile.bio }}</textarea>
                        <br>
                        <label for="id_avatar">Аватар:</label>
                        <img src="{{ profile.get_avatar_url }}" alt="Аватар пользователя">
                        <input type="file" id="id_avatar" name="avatar">
                        <br>
                        <label for="delete_avatar">Удалить фото:</label>
                        <input type="checkbox" id="delete_avatar" name="delete_avatar" value="true">

                        <br>
                        <input type="submit" value="Сохранить">
                    </form>

                    <a href="{% url 'view_profile' %}">Вернуться</a>
                {% endblock %}
            </div>

        </div>
    </div>
</body>
</html>

userSystem/templates/userSystem/login.html
{% extends "mySite/base.html" %}
{% load static %}

{% block title %}register{% endblock %}

{% block content %}

<main class="p-0 m-0 pr-3">
    <div class=" flex max-md:flex-col max-md:items-stretch max-md:gap-0">
      <div class="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
        <register1 class="bg-violet-300 flex grow flex-col w-full pl-20 pr-14 py-12 items-end max-md:max-w-full max-md:px-5">
          <h1 class="text-blue-950 text-6xl max-w-[764px] mt-28 max-md:max-w-full max-md:text-4xl max-md:mt-10">Добро пожаловать!)</h1>
          <div class="text-blue-950 text-center text-4xl max-w-[402px] mt-[745px] mb-3 max-md:mt-10">для покупки билетов <a class="underline" href="{% url 'login' %}">Войдите</a> или <a class="underline" href="{% url 'register' %}">зарегистрируйтесь</a></div>
        </register1>
      </div>
      <div class="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
        <register2 class="bg-amber-100 flex grow flex-col justify-center w-full px-16 py-12 items-end max-md:max-w-full max-md:px-5">
          <div class="flex w-[649px] max-w-full flex-col items-center mr-14 mt-44 mb-60 max-md:mr-2.5 max-md:my-10">
            <h2 class="text-yellow-900 text-4xl whitespace-nowrap max-md:max-w-full">Войти</h2>
            <div class="self-stretch mt-32 max-md:max-w-full max-md:mt-10">
              <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                <div class="flex flex-col items-stretch w-[24%] max-md:w-full max-md:ml-0">
                  <div class="flex flex-col items-stretch mt-6 max-md:mt-10">
                    <!-- <div class="text-yellow-900 text-3xl">почта</div>
                    <div class="text-yellow-900 text-3xl mt-16 max-md:mt-10">телефон</div>
                    <div class="text-yellow-900 text-3xl mt-14 max-md:mt-10">никнейм</div> -->
                  </div>
                </div>
                <div class="flex flex-col items-stretch w-[76%] ml-5 max-md:w-full max-md:ml-0">
                  <div class="flex grow flex-col items-stretch max-md:max-w-full max-md:mt-10">
                    <form class="register__form" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    <!-- <input type="text" id="email" class="border bg-white flex shrink-0 h-[51px] flex-col rounded-lg border-solid border-black max-md:max-w-full" aria-label="Email" />
                    <input type="text" id="phone" class="border bg-white flex shrink-0 h-[51px] flex-col mt-9 rounded-lg border-solid border-black max-md:max-w-full" aria-label="Phone" />
                    <input type="text" id="nickname" class="border bg-white flex shrink-0 h-[51px] flex-col mt-9 rounded-lg border-solid border-black max-md:max-w-full" aria-label="Nickname" /> -->
                    <div class="text-black text-2xl mt-10 max-md:max-w-full">нет аккаунта? <a class="underline" href="{% url 'register' %}">зарегистрируйтесь</a></div>
                    <button class="text-white text-center text-2xl whitespace-nowrap bg-violet-500 justify-center items-stretch mt-10 px-3.5 py-4 rounded-3xl max-md:max-w-full">Войти</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </register2>
      </div>
    </div>
</main>

</form>
{% endblock %}

userSystem/templates/userSystem/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <h2>Вы вышли из своей учетной записи</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Войти</a>
        </small>
    </div>
{% endblock content %}

userSystem/templates/userSystem/other_user_profile.html
{% extends "mySite/base.html" %}
{% block content %}
{% if profile %}
    <h2>Профиль пользователя</h2>
    <p>Имя пользователя: {{ profile.user.username }}</p>
    <p>Почта: {{ profile.user.email }}</p>

    <p>Уровень: {{ profile.get_level_display }}</p>

    <p>Имя: {{ profile.name }}</p>
    <p>Фамилия: {{ profile.surname }}</p>
    <p>Биография: {{ profile.bio }}</p>

    <p>Аватар:</strong></p>
    <img src="{{ profile.get_avatar_url }}" alt="Аватар пользователя">

    <p>Дата регистрации: {{ profile.user.date_joined }}</p>
    <p>Последний вход: {{ profile.user.last_login }}</p>

{% else %}
    <p>{{ error_message }}</p>
{% endif %}

{% endblock %}

userSystem/templates/userSystem/register.html
{% extends "mySite/base.html" %}
{% load static %}

{% block title %}register{% endblock %}

{% block content %}

<main class="bg-white pr-3">
    <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
      <div class="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
        <register1 class="bg-violet-300 flex grow flex-col w-full pl-20 pr-14 py-12 items-end max-md:max-w-full max-md:px-5">
          <h1 class="text-blue-950 text-6xl max-w-[764px] mt-28 max-md:max-w-full max-md:text-4xl max-md:mt-10">Добро пожаловать!)</h1>
          <div class="text-blue-950 text-center text-4xl max-w-[402px] mt-[745px] mb-3 max-md:mt-10">для покупки билетов <a class="underline" href="{% url 'login' %}">Войдите</a> или <a class="underline" href="{% url 'register' %}">зарегистрируйтесь</a></div>
        </register1>
      </div>
      <div class="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
        <register2 class="bg-amber-100 flex grow flex-col justify-center w-full px-16 py-12 items-end max-md:max-w-full max-md:px-5">
          <div class="flex w-[649px] max-w-full flex-col items-center mr-14 mt-44 mb-60 max-md:mr-2.5 max-md:my-10">
            <h2 class="text-yellow-900 text-4xl whitespace-nowrap max-md:max-w-full">Зарегистрироваться</h2>
            <div class="self-stretch mt-32 max-md:max-w-full max-md:mt-10">
              <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                <div class="flex flex-col items-stretch w-[24%] max-md:w-full max-md:ml-0">
                  <div class="flex flex-col items-stretch mt-6 max-md:mt-10">
                    <!-- <div class="text-yellow-900 text-3xl">почта</div>
                    <div class="text-yellow-900 text-3xl mt-16 max-md:mt-10">телефон</div>
                    <div class="text-yellow-900 text-3xl mt-14 max-md:mt-10">никнейм</div> -->
                  </div>
                </div>
                <div class="flex flex-col items-stretch w-[76%] ml-5 max-md:w-full max-md:ml-0">
                  <div class="flex grow flex-col items-stretch max-md:max-w-full max-md:mt-10">
                    <form class="register__form" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    <!-- <input type="text" id="email" class="border bg-white flex shrink-0 h-[51px] flex-col rounded-lg border-solid border-black max-md:max-w-full" aria-label="Email" />
                    <input type="text" id="phone" class="border bg-white flex shrink-0 h-[51px] flex-col mt-9 rounded-lg border-solid border-black max-md:max-w-full" aria-label="Phone" />
                    <input type="text" id="nickname" class="border bg-white flex shrink-0 h-[51px] flex-col mt-9 rounded-lg border-solid border-black max-md:max-w-full" aria-label="Nickname" /> -->
                    <div class="text-black text-2xl mt-10 max-md:max-w-full">уже есть аккаунт? <a class="underline" href="{% url 'login' %}">Войдите</a></div>
                    <button class="text-white text-center text-2xl whitespace-nowrap bg-violet-500 justify-center items-stretch mt-10 px-3.5 py-4 rounded-3xl max-md:max-w-full">Зарегистрироваться</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </register2>
      </div>
    </div>
</main>

</form>
{% endblock %}

userSystem/templates/userSystem/view_profile.html
{% extends "mySite/base.html" %}

{% block title %}view profile{% endblock %}
{% block content %}

{% if user == request.user or profile.visibility == 'public' %}

<header class="bg-white flex flex-col justify-center items-center px-16 py-12 max-md:px-5">
    <div class="flex w-full max-w-[1644px] flex-col mt-20 mb-8 items-start max-md:max-w-full max-md:mt-10">
      <div class="w-[570px] max-w-full">
        <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div class="flex flex-col items-stretch w-[58%] max-md:w-full max-md:ml-0">
            <img src="{{ profile.get_avatar_url }}" class="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-10" alt="Аватар пользователя">
            </div>
          <div class="flex flex-col items-stretch w-[42%] ml-5 max-md:w-full max-md:ml-0">
            <div class="text-black text-5xl my-auto max-md:text-4xl max-md:mt-10">Никнейм:&nbsp;{{ user.username }}</div>
            <div class="text-black text-5xl my-auto max-md:text-4xl max-md:mt-10">Имя:&nbsp;{{ profile.name }}</div>
            <div class="text-black text-5xl my-auto max-md:text-4xl max-md:mt-10">Фамилия:&nbsp;{{ profile.surname }}</div>
            {% if user == request.user %}
                <a href="{% url 'edit_profile' %}">Редактировать профиль</a>
                <a href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="text-black text-5xl self-center max-w-[471px] mt-40 max-md:text-4xl max-md:mt-10">история покупок</div>
      <div class="bg-fuchsia-400 bg-opacity-50 self-stretch flex flex-col justify-center mt-8 px-16 py-12 rounded-[37px] items-end max-md:max-w-full max-md:px-5">
        <div class="bg-fuchsia-200 flex w-[821px] max-w-full flex-col items-stretch mr-20 mt-7 mb-60 pl-8 pr-16 pt-11 pb-7 rounded-[62px] max-md:mr-2.5 max-md:mb-10 max-md:px-5">
          <div class="text-black text-3xl max-md:max-w-full">название:</div>
          <div class="text-black text-3xl mt-6 max-md:max-w-full">дата и время:</div>
          <div class="mt-4 max-md:max-w-full">
            <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
              <div class="flex flex-col items-stretch w-[24%] max-md:w-full max-md:ml-0">
                <div class="text-black text-3xl max-md:mt-8">описание:</div>
              </div>
              <div class="flex flex-col items-stretch w-[76%] ml-5 max-md:w-full max-md:ml-0">
                <div class="bg-zinc-100 flex w-[530px] shrink-0 max-w-full h-[132px] flex-col mx-auto rounded-xl max-md:mt-7"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


{% else %}
    <p>Этот профиль приватный, и доступ к нему ограничен.</p>
{% endif %}


{% endblock %}