benches/urls.py
from django.urls import path
from . import views

app_name = 'benches'

urlpatterns = [
    path('create_bench/', views.create_bench, name='create_bench'),
    path('', views.bench_list, name='bench_list'),

    path('event/<int:bench_id>/', views.bench_detail, name='bench_detail'),

    
]

cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

mySite/urls.py
from django.urls import path
from . import views

app_name = 'mySite'

urlpatterns = [
    path('', views.index, name='index'),

    
]

ticketer/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from userSystem import views as user_views

app_name = 'mySite'

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/reread-logo.ico', permanent=True), name='favicon'),
    path('admin/', admin.site.urls),
    path('', include('mySite.urls')),


    # login system
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),

    # profile system
    path('profile/', user_views.view_profile, name='view_profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),

    path('profile/<str:username>/', user_views.other_user_profile, name='other_user_profile'),

    path('', include('benches.urls')),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),

    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mySite/views.py
from django.shortcuts import render
from benches.models import Bench

from userSystem.models import Profile

def index(request):
    benches = Bench.objects.all()

    if request.user.is_authenticated:
        try:
            profile = Profile.objects.get(user=request.user)
        except Profile.DoesNotExist:
            # Если профиль не существует, создайте его здесь
            profile = Profile(user=request.user)
            profile.save()
        profile = Profile.objects.get(user=request.user)
        return render(request, "mySite/index.html", {'profile': profile, 'benches': benches})
    else:
            return render(request, 'mySite/index.html', {'benches': benches})


# ПОФИКСИТЬ КОСТЫЛЬ С ОТОБРАЖЕНИЕМ ФОТО, СДЕЛАТЬ ПРОВЕРКУ В ШАБЛОНЕ

mySite/templates/mySite/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}

    <title>
        {% block title %}{% endblock %} — Тикетон
    </title>

</head>
<body class="font-sans">

    {% include 'mySite/header.html' %}

    <div class="main">
        {% block content %}{% endblock %}
    </div>


    {% include 'mySite/footer.html' %}

    

</body>
</html>

mySite/templates/mySite/event_detail.html
{% extends "mySite/base.html" %}
{% load static tailwind_tags %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class="bg-white flex flex-col items-center pb-12">
    <div
      class="text-neutral-400 text-xl whitespace-nowrap self-stretch w-full justify-center px-16 py-11 items-start max-md:max-w-full max-md:pl-8 max-md:pr-5"
    >   
        <a href="/">Главная</a> →
        <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>  →
        {{ product.name }}
    </div>
    <div
      class="flex w-full max-w-[1132px] flex-col mt-12 px-5 max-md:max-w-full max-md:mt-10"
    >
      <div class="text-black text-5xl self-center whitespace-nowrap ml-24">
        {{ product.name }}
      </div>
      <div
        class="text-neutral-400 text-2xl font-medium self-center whitespace-nowrap mt-3.5"
      >
      {{ product.price }} тг
      </div>
      <div
        class="flex w-[860px] max-w-full justify-between gap-5 ml-16 mt-11 self-start items-start max-md:flex-wrap max-md:mt-10"
      >
        <img
          loading="lazy"
          src="{{ product.image.url }}"
          class="aspect-[0.68] object-contain object-center w-[400px] fill-black overflow-hidden shrink-0 max-w-full"
        />
        <div
          class="flex grow basis-[0%] flex-col items-stretch mt-11 self-end max-md:mt-10"
        >
          <div class="text-black text-sm">
            {{ product.description }}
            <br />
            <br />
          </div>
          <div
            class="flex items-stretch justify-between gap-5 mt-24 max-md:mt-10"
          >
            <div
              class="text-black text-xl whitespace-nowrap border grow justify-center pl-12 pr-16 py-6 rounded-2xl border-solid border-black items-start max-md:px-5"
            >
            <form action="{% url "cart:cart_add" product.id %}" method="post" class="">
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину" class="underline underline-offset-4 cursor-pointer">
                
    <label for="id_quantity">:</label>
    
      
      <select name="quantity" id="id_quantity">
  <option value="1">1</option>

  <option value="2">2</option>

  <option value="3">3</option>

  <option value="4">4</option>

  <option value="5">5</option>

  <option value="6">6</option>

  <option value="7">7</option>

  <option value="8">8</option>

  <option value="9">9</option>

  <option value="10">10</option>

  <option value="11">11</option>

  <option value="12">12</option>

  <option value="13">13</option>

  <option value="14">14</option>

  <option value="15">15</option>

  <option value="16">16</option>

  <option value="17">17</option>

  <option value="18">18</option>

  <option value="19">19</option>

  <option value="20">20</option>

</select>
      
{% csrf_token %}
        <input type="hidden" name="update" value="False" id="id_update">
      
    
  
                <label for="id_quantity"></label>
                <input type="hidden" name="csrfmiddlewaretoken" value="x7VjSgjpOJK5eRbVyHK2y3aIsoHcIBIDmU6lurLb5AdY8rEoGwp3IiEmdOoPO5Zz">

            </form>
            </div>
          </div>
        </div>
      </div>
      <div
        class="bg-zinc-300 w-[605px] shrink-0 max-w-full h-px mt-36 self-end max-md:mt-10"
      ></div>
      <div
        class="text-black text-2xl font-medium self-center whitespace-nowrap mt-10"
      >
        Description
      </div>
      <div
        class="text-neutral-400 text-justify text-base self-stretch mt-20 max-md:max-w-full max-md:mt-10"
      >
      {{ product.description }}
      </div>
    </div>
    <div
      class="bg-zinc-300 self-stretch min-h-[1px] w-full mb-16 max-md:max-w-full max-md:mb-10"
    ></div>
  </div>

    <div class="product-detail bg-green-400">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.jpg" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
    </div>
{% endblock %}

mySite/templates/mySite/footer.html
{% load static %}
{% load static tailwind_tags %}
<hr>
<footer class="bg-white flex items-stretch justify-between gap-5 pr-20 pt-3 max-md:flex-wrap max-md:pr-5">
  
  <div class="flex items-stretch justify-between gap-0">
    <img loading="lazy" srcset="https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/142f2d9a849d467f4a0c6eda51ed4d5fee335458e2806ef8fade9567b003dc52?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"class="aspect-[1.43] object-contain object-center w-[183px] overflow-hidden shrink-0 max-w-full" />
    <div class="text-black text-2xl my-auto">Made with AltynaiTeam</div>
  </div>
  <div class="self-center flex items-stretch gap-3 my-auto">
    <img loading="lazy" srcset="https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ae260bcc2cd9adc5891383a3ababd07802311dde8a3f45eebcff784e84054e29?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"class="aspect-square object-contain object-center w-10 overflow-hidden shrink-0 max-w-full" />
    <div class="text-black text-2xl self-center grow whitespace-nowrap my-auto"> @altynaio_o </div>
  </div>
  <div class="self-center flex items-stretch gap-2 my-auto">
    <img loading="lazy" srcset="https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/7b7442ab624daf87f2a3f8b6e09d92a89ab63210acf96471b5f1c47e9b496c14?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"class="aspect-square object-contain object-center w-10 overflow-hidden shrink-0 max-w-full" />
    <div class="text-black text-2xl self-center grow whitespace-nowrap my-auto"> @Altynai10101 </div>
  </div>
</footer>
<hr>

mySite/templates/mySite/header.html
{% load static %}
{% load static tailwind_tags %}

<header class="bg-violet-500 flex items-stretch justify-between gap-5 pl-7 pr-20 rounded-sm max-md:flex-wrap max-md:px-5">
  <div class="flex items-start justify-between gap-5 max-md:max-w-full max-md:flex-wrap max-md:justify-center">
    <a href="{% url 'mySite:index' %}" class="w-20">
      <img src="{% static '/img/билет.png' %}" class=""/>
    </a>

    <!-- <input class="bg-white self-center flex w-[610px] shrink-0 max-w-full h-14 flex-col my-auto rounded-3xl" type="text">
    <a href="" class="text-blue-900 text-center text-3xl bg-zinc-300 self-center justify-center items-stretch my-auto px-4 py-5 rounded-3xl">поиск</a>
    <a href="" class="text-blue-900 text-3xl bg-zinc-300 self-center justify-center items-stretch my-auto pl-7 pr-4 py-4 rounded-3xl max-md:pl-5">фильтр</a> -->
    
  </div>
  <div class="flex flex-row">
    {% if user.is_authenticated %}
    <div class="mt-8 pr-10">
      <a href="{% url "cart:cart_detail" %}">
        <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4f9e8a794d27ac72dd1461801cbff589a0a46bf0032d5f358be3e9b224b69aa3?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"
        class="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
      />
    </a>


    </div>
    <a href="{% url 'view_profile' %}" class="text-indigo-950 text-4xl self-center grow whitespace-nowrap my-auto pr-10">профиль</a>
    <a href="{% url 'logout' %}" class="text-indigo-950 text-4xl self-center grow whitespace-nowrap my-auto pr-10">Выйти</a>
  {% else %}
    <a href="{% url 'login' %}" class="text-indigo-950 text-4xl self-center grow whitespace-nowrap my-auto pr-10">Войти</a>
    <a href="{% url 'register' %}" class="text-indigo-950 text-4xl self-center grow whitespace-nowrap my-auto pr-10">Зарегистрироваться</a>
  {% endif %}
    
  </div>  

</header>

mySite/templates/mySite/index.html
{% extends "mySite/base.html" %}
{% block title %}index{% endblock %}

{% block content %}


<div
  class="bg-white flex flex-col justify-center items-center px-16 py-12 max-md:px-5"
>
  <div
    class="flex w-full max-w-[1440px] flex-col items-stretch mt-11 mb-32 max-md:max-w-full max-md:my-10"
  >
  {% for bench in benches %}
  <div class="mt-24 max-md:max-w-full max-md:mt-10">
	  <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
		<div
		  class="flex flex-col items-stretch w-[28%] max-md:w-full max-md:ml-0"
		>
		  <img class="aspect-[1.04] object-contain object-center w-[341px] overflow-hidden shrink-0 max-w-full grow max-md:mt-10"
		  src="{{ bench.get_avatar_url }}" alt="">
		</div>
		<div
		  class="flex flex-col items-stretch w-[72%] ml-5 max-md:w-full max-md:ml-0"
		>
		  <div
			class="bg-fuchsia-200 grow w-full pl-9 pr-20 pt-12 pb-7 rounded-[62px] max-md:max-w-full max-md:mt-10 max-md:px-5"
		  >
			<div
			  class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0"
			>
			  <div
				class="flex flex-col items-stretch w-[27%] max-md:w-full max-md:ml-0"
			  >
				<div class="flex flex-col items-stretch max-md:mt-10 ">
				  <a href="{% url 'benches:bench_detail' bench.id %}" class="text-black text-3xl whitespace-nowrap">Название: {{ bench.name }} <br><br> Цена: {{ bench.price }} тенге</a>
				  <div class="text-black text-3xl mt-8 ">Дата: {{ bench.created_date }}</div>
				  <div class="text-black text-3xl mt-6 ">Адрес: {{ bench.district }}</div>
				</div>
			  </div>
			  <div
				class="flex flex-col items-stretch w-[73%] ml-5 max-md:w-full max-md:ml-0"
			  >
				<div
				  class="bg-zinc-100 flex w-[619px] shrink-0 max-w-full h-[149px] flex-col mt-24 mx-auto rounded-xl max-md:mt-10"><p class="text-center">{{ bench.deskription }}</p></div>
			  </div>
			</div>
		  </div>
		</div>
	  </div>
	</div>
  
	{% endfor %}
  </div>
</div>

{% endblock content %}