cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path, include
from orders import views


urlpatterns = [
    path('', views.order_create, name='order_create'),
]

ticketer/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from userSystem import views as user_views

app_name = 'mySite'

urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/reread-logo.ico', permanent=True), name='favicon'),
    path('admin/', admin.site.urls),
    path('', include('mySite.urls')),


    # login system
    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),
    path('logout/', user_views.user_logout, name='logout'),

    # profile system
    path('profile/', user_views.view_profile, name='view_profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),

    path('profile/<str:username>/', user_views.other_user_profile, name='other_user_profile'),

    path('', include('benches.urls')),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),

    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from benches.models import Bench as Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)  # Добавьте аргумент on_delete
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)  # Добавьте аргумент on_delete
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created

def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
        # очистка корзины
        cart.clear()
        # запуск асинхронной задачи
        order_created.delay(order.id)
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

orders/templates/orders/order/create.html
{% extends "mySite/base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div
  class="mt-20 xl:ml-40 xl:mr-40 bg-violet-500 flex flex-col items-stretch my-auto px-8 py-9 rounded-[33.892px] max-md:max-w-full max-md:mt-10 max-md:px-5"
>
  <div
    class="text-white text-4xl font-semibold grow whitespace-nowrap items-center justify-between gap-5 max-md:max-w-full max-md:flex-wrap"
  >
    Оформление заказа
  </div>
  <div class="text-white text-3xl font-medium mt-8 max-md:max-w-full">
    Выбранные товары
  </div>
  <div
    class="text-black text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5"
  >
    {% for item in cart %}
    <li>
        {{ item.quantity }} билета на {{ item.product.name }} -
        <span>{{ item.total_price }} тг</span>
    </li>
    {% endfor %}
  </div>
  <form action="." method="post" class="order-form ">
  <div
    class="flex items-stretch justify-between gap-5 mt-7 max-md:max-w-full max-md:flex-wrap max-md:justify-center"
  >
</div>

  <div
    class="text-white text-2xl font-medium mt-4 max-md:max-w-full max-md:mt-10">
        Имя
  </div>
  <input type="text" name="first_name" maxlength="50" required="" id="id_first_name" class="text-stone-300 text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5">

    <div
    class="text-white text-2xl font-medium mt-4 max-md:max-w-full max-md:mt-10">
        Фамилия
  </div>
  <input type="text" name="last_name" maxlength="50" required="" id="id_last_name" class="text-stone-300 text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5">
  
      <div
    class="text-white text-2xl font-medium mt-4 max-md:max-w-full max-md:mt-10">
    Email
  </div>
  <input type="email" name="email" maxlength="50" required="" id="id_email" class="text-stone-300 text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5">
  
    <div
    class="text-white text-2xl font-medium mt-4 max-md:max-w-full max-md:mt-10">
        Адрес
  </div>
  <input type="text" name="address" maxlength="50" required="" id="id_address" class="text-stone-300 text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5">
  
    <div
    class="text-white text-2xl font-medium mt-4 max-md:max-w-full max-md:mt-10">
        Индекс
  </div>
  <input type="text" name="postal_code" maxlength="50" required="" id="id_postal_code" class="text-stone-300 text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5">
        <div
    class="text-white text-2xl font-medium mt-4 max-md:max-w-full max-md:mt-10">
        Город
  </div>
  <input type="text" name="city" maxlength="50" required="" id="id_city" class="text-stone-300 text-xl font-medium whitespace-nowrap bg-violet-300 justify-center mt-5 pl-8 pr-16 py-7 rounded-xl items-start max-md:max-w-full max-md:px-5">
  
  
  <div class="mt-8 max-md:max-w-full">
    <div class="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
      <div class="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
        
    </div>
  </div>
  <div class="bg-violet-300 shrink-0 h-0.5 mt-9 max-md:max-w-full"></div>
  <div
    class="flex items-stretch justify-between gap-5 mt-8 max-md:max-w-full max-md:flex-wrap"
  >
    <div class="flex grow basis-[0%] flex-col items-stretch">
      <div class="text-white text-2xl font-medium mt-5">К оплате</div>
    </div>
    <div class="flex basis-[0%] flex-col items-end">
      <div class="text-green-500 text-right text-2xl font-medium mt-6">
        Бесплатно
      </div>
      <div class="text-white text-right text-2xl font-medium self-stretch mt-6 whitespace-nowrap">
        {{ cart.get_total_price }} тг
      </div>
    </div>
  </div>
  <div
    class="bg-violet-900 flex w-full items-center justify-between gap-5 mt-12 pl-10 pr-9 py-8 rounded-3xl max-md:max-w-full max-md:flex-wrap max-md:mt-10 max-md:px-5"
  >
    <div class="self-stretch flex items-center justify-between gap-3.5">
      <div
        class="text-white text-3xl font-medium grow whitespace-nowrap my-auto"
      >


            <p><input type="submit" value="Оформить заказ"></p>
            {% csrf_token %}
        </form>
      </div>
      <img
        loading="lazy"
        srcset="https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/cec03e980a49f46fcd210c54fa83cee7262471d9753fb15097d2695a8807123a?apiKey=fa4215c420a442bf87a69fcbffc5ead0&"
        class="aspect-square object-contain object-center w-[43px] overflow-hidden self-stretch shrink-0 max-w-full"
      />
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "mySite/base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<div class="mt-10 ml-10 text-xl">
    <h1>Спасибо за заказ!</h1>
    <p>Ваш заказ успешно обработан. Номер вашего заказа
        <strong>{{ order.id }}</strong>.</p>
        <br>
    <a class="text-2xl" href="/">
        Вернуться на главную
    </a>
    
</div>
{% endblock %}